### PR TITLE
Merge Milestone 2

### PR DESCRIPTION
**Pull request by nkryuchkov**
Partially fixes https://github.com/SkycoinProject/skywire-mainnet/issues/159

 Changes:	
- Resolved conflicts between `milestone2` and `master`

### CODE REVIEW

**Comment by evanlinjin** [comment]
Should we fork `nettest` and comment out the timeout tests?

**Comment by nkryuchkov** [comment]
@evanlinjin For resolving `dmsg` failing tests issue?

**Comment by evanlinjin** [comment]
> @evanlinjin For resolving `dmsg` failing tests issue?

Yes.

**Comment by nkryuchkov** [comment]
@evanlinjin I would rather try to fix in long-term. But I don't mind commenting it out and merging for now, but I think we need to fix it later.

**Pull request merged**
